#!/usr/bin/with-contenv bash
#=================================================
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/docker-aria2-pro
# Description: A perfect Aria2 Docker image
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================

Green_font_prefix="\033[32m"
Red_font_prefix="\033[31m"
Green_background_prefix="\033[42;37m"
Red_background_prefix="\033[41;37m"
Font_color_suffix="\033[0m"
INFO="[${Green_font_prefix}INFO${Font_color_suffix}]"
ERROR="[${Red_font_prefix}ERROR${Font_color_suffix}]"

mkdir -p /config && cd /config

while [[ ! -f aria2.conf ]]; do
    echo
    echo -e "${INFO} Download 'aria2.conf' ..."
    curl -fsSLO https://p3terx.github.io/aria2.conf/aria2.conf ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/aria2.conf ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/aria2.conf
    [[ -s aria2.conf ]] && {
        sed -i "s@^\(rpc-listen-port=\).*@\1${RPC_PORT:-6800}@" aria2.conf
        sed -i "s@^\(listen-port=\).*@\1${LISTEN_PORT:-6888}@" aria2.conf
        sed -i "s@^\(dht-listen-port=\).*@\1${LISTEN_PORT:-6888}@" aria2.conf
        sed -i "s@^\(dir=\).*@\1/downloads@" aria2.conf
        sed -i "s@root/.aria2@config@" aria2.conf
        [[ $TZ != "Asia/Shanghai" ]] && sed -i '9,$s/#.*//;/^$/d' aria2.conf
    } || {
        echo
        echo -e "${ERROR} 'aria2.conf' download error, retry ..."
        sleep 5
    }
done

while [[ ! -f delete.aria2.sh ]]; do
    echo
    echo -e "${INFO} Download 'delete.aria2.sh' ..."
    curl -fsSLO https://p3terx.github.io/aria2.conf/delete.aria2.sh ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/delete.aria2.sh ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/delete.aria2.sh
    [[ -s delete.aria2.sh ]] || {
        echo
        echo -e "${ERROR} 'delete.aria2.sh' download error, retry ..."
        sleep 5
    }
done

while [[ ! -f delete.sh ]]; do
    echo
    echo -e "${INFO} Download 'delete.sh' ..."
    curl -fsSLO https://p3terx.github.io/aria2.conf/delete.sh ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/delete.sh ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/delete.sh
    [[ -s delete.sh ]] || {
        echo
        echo -e "${ERROR} 'delete.sh' download error, retry ..."
        sleep 5
    }
done

while [[ ! -f dht.dat ]]; do
    echo
    echo -e "${INFO} Download 'dht.dat' ..."
    curl -fsSLO https://p3terx.github.io/aria2.conf/dht.dat ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/dht.dat ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/dht.dat
    [[ -s dht.dat ]] || {
        echo
        echo -e "${ERROR} 'dht.dat' download error, retry ..."
        sleep 5
    }
done

while [[ ! -f dht6.dat ]]; do
    echo
    echo -e "${INFO} Download 'dht6.dat' ..."
    curl -fsSLO https://p3terx.github.io/aria2.conf/dht6.dat ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/dht6.dat ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/dht6.dat
    [[ -s dht6.dat ]] || {
        echo
        echo -e "${ERROR} 'dht6.dat' download error, retry ..."
        sleep 5
    }
done

[[ -f aria2.session ]] || touch aria2.session

if [[ "$TRACKERS" != "no" ]]; then
    rm -f /etc/services.d/crond/down
    bash <(
        curl -fsSL https://p3terx.github.io/aria2.conf/tracker.sh ||
            curl -fsSL https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/tracker.sh ||
            curl -fsSL https://gh.p3terx.workers.dev/aria2.conf/master/tracker.sh
    )
fi
exit 0
