#!/usr/bin/with-contenv bash
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/docker-aria2-pro
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

cd /config
. /etc/init-base

PROFILE_LIST="
aria2.conf
delete.sh
dht.dat
dht6.dat
LICENSE
"

DOWNLOAD_PROFILE

[[ ! -f aria2.session ]] && {
    rm -rf aria2.session
    touch aria2.session
}

if ! [[ "$UPDATE_TRACKERS" = "false" || "$UPDATE_TRACKERS" = "disable" ]]; then
    rm -f /etc/services.d/crond/down
    bash <(
        curl ${CURL_OPTIONS} ${PROFILE_URL1}/tracker.sh ||
            curl ${CURL_OPTIONS} ${PROFILE_URL2}/tracker.sh ||
            curl ${CURL_OPTIONS} ${PROFILE_URL3}/tracker.sh
    )
fi

exit 0
