#!/usr/bin/with-contenv bash
#=================================================
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/docker-aria2-pro
# Description: A perfect Aria2 Docker image
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================

cd /config
. /etc/init-base

UPLOAD_MODE() {
    echo
    echo -e "${INFO} Installing RCLONE ..."
    [[ -L /usr/bin/unzip ]] && rm -f /usr/bin/unzip
    curl -fsSL https://rclone.org/install.sh | bash
    [[ -f rclone/rclone.conf ]] && {
        mv rclone/rclone.conf .
        rm -rf rclone
    }
    PROFILE="upload.sh"
    DOWNLOAD_PROFILE
}

MOVE_MODE() {
    PROFILE="move.sh"
    DOWNLOAD_PROFILE
}

if [[ "$SPECIAL_MODE" = "rclone" || "$RCLONE" = "enable" ]]; then
    [[ -e "autoupload.sh" ]] && mv -f autoupload.sh upload.sh
    UPLOAD_MODE
elif [[ "$SPECIAL_MODE" = "move" ]]; then
    MOVE_MODE
fi

exit 0
