#!/bin/sh
#=================================================
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/docker-aria2-pro
# Description: A perfect Aria2 Docker image
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================

chown -R p3terx:p3terx /config
chown -R p3terx:p3terx /downloads
chmod 700 /config/*.sh
chmod 600 /config/*.conf
