#!/bin/sh
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Docker-Aria2-Pro
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

. /etc/init-base
chown -R p3terx:p3terx ${DOWNLOAD_DIR}
chown -R p3terx:p3terx ${ARIA2_CONF_DIR}
chmod 600 ${ARIA2_CONF_DIR}/*
chmod 755 ${SCRIPT_DIR}
chmod 700 ${SCRIPT_DIR}/*
