#!/usr/bin/with-contenv bash
#=================================================
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/docker-aria2-pro
# Description: A perfect Aria2 Docker image
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================
Green_font_prefix="\033[32m"
Red_font_prefix="\033[31m"
Green_background_prefix="\033[42;37m"
Red_background_prefix="\033[41;37m"
Font_color_suffix="\033[0m"
INFO="[${Green_font_prefix}INFO${Font_color_suffix}]"
ERROR="[${Red_font_prefix}ERROR${Font_color_suffix}]"

mkdir -p /config && cd /config

while [[ ! -e aria2.conf ]]; do
    echo
    echo -e "${INFO} Doanload 'aria2.conf' ..."
    curl -fsSLO https://raw.githubusercontent.com/P3TERX/aria2.conf/master/aria2.conf ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/aria2.conf ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/aria2.conf
    [[ -e aria2.conf ]] || {
        echo
        echo -e "${ERROR} 'aria2.conf' doanload error, retry ..."
        sleep 5
    }
done

while [[ ! -e delete.aria2.sh ]]; do
    echo
    echo -e "${INFO} Doanload 'delete.aria2.sh' ..."
    curl -fsSLO https://raw.githubusercontent.com/P3TERX/aria2.conf/master/delete.aria2.sh ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/delete.aria2.sh ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/delete.aria2.sh
    [[ -e delete.aria2.sh ]] || {
        echo
        echo -e "${ERROR} 'delete.aria2.sh' doanload error, retry ..."
        sleep 5
    }
done

while [[ ! -e delete.sh ]]; do
    echo
    echo -e "${INFO} Doanload 'delete.sh' ..."
    curl -fsSLO https://raw.githubusercontent.com/P3TERX/aria2.conf/master/delete.sh ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/delete.sh ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/delete.sh
    [[ -e delete.sh ]] || {
        echo
        echo -e "${ERROR} 'delete.sh' doanload error, retry ..."
        sleep 5
    }
done

while [[ ! -e dht.dat ]]; do
    echo
    echo -e "${INFO} Doanload 'dht.dat' ..."
    curl -fsSLO https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht.dat ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/dht.dat ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/dht.dat
    [[ -e dht.dat ]] || {
        echo
        echo -e "${ERROR} 'dht.dat' doanload error, retry ..."
        sleep 5
    }
done

while [[ ! -e dht6.dat ]]; do
    echo
    echo -e "${INFO} Doanload 'dht6.dat' ..."
    curl -fsSLO https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht6.dat ||
        curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/dht6.dat ||
        curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/dht6.dat
    [[ -e dht6.dat ]] || {
        echo
        echo -e "${ERROR} 'dht6.dat' doanload error, retry ..."
        sleep 5
    }
done

[[ -e aria2.session ]] || touch aria2.session

[[ "$TRACKERS" = "no" ]] ||
    bash <(
        curl -fsSL git.io/tracker.sh ||
            curl -fsSL https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/tracker.sh ||
            curl -fsSL https://gh.p3terx.workers.dev/aria2.conf/master/tracker.sh
    )
