#!/usr/bin/with-contenv bash
#=================================================
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/docker-aria2-pro
# Description: A perfect Aria2 Docker image
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================

Green_font_prefix="\033[32m"
Red_font_prefix="\033[31m"
Green_background_prefix="\033[42;37m"
Red_background_prefix="\033[41;37m"
Font_color_suffix="\033[0m"
INFO="[${Green_font_prefix}INFO${Font_color_suffix}]"
ERROR="[${Red_font_prefix}ERROR${Font_color_suffix}]"

if [[ "$SPECIAL_MODE" = "move" ]]; then
    cd /config
    while [[ ! -f move.sh ]]; do
        echo
        echo -e "${INFO} Download 'move.sh' ..."
        curl -fsSLO https://p3terx.github.io/aria2.conf/move.sh ||
            curl -fsSLO https://cdn.jsdelivr.net/gh/P3TERX/aria2.conf/move.sh ||
            curl -fsSLO https://gh.p3terx.workers.dev/aria2.conf/master/move.sh
        [[ -s move.sh ]] && {
            sed -i "s@^\(DOWNLOAD_PATH='\).*@\1/downloads'@" move.sh
            sed -i "s@^\(TARGET_DIR='\).*@\1/downloads/completed'@" move.sh
            sed -i "s@\(LOG_PATH='\).*@\1/config/move.log'@" move.sh
        } || {
            echo
            echo -e "${ERROR} 'move.sh' download error, retry ..."
            sleep 5
        }
    done
fi
exit 0
